### ISSUE TITLE
Problem PublicKey download Tools

### ISSUE THREAD

**Issue by KlausItem** [Te-k/harpoontools#2]
What is wrong ???
```
Collecting git+ssh://git@github.com/Te-k/harpoontools
  Cloning ssh://git@github.com/Te-k/harpoontools to /tmp/pip-req-build-l3bxagr2
Permission denied (publickey).
fatal: Could not read from remote repository.
```
THX

**Comment by Te-k** [comment]
The link here uses ssh so you need to have public/private key setup in github. You can use the https url instead : `pip install git+https://git@github.com/Te-k/harpoontools`

**Comment by KlausItem** [comment]
That does the Trick ;-)

THX
