### ISSUE TITLE
fails with conflicting lxml

### ISSUE THREAD

**Issue by anarcat** [Te-k/harpoontools#3]
I have tried to install harpoontools in a container with harpoon already installed, and it failed with this:

```
root@044648aced56:/usr/src# pip install harpoontools --break-system-packages
Collecting harpoontools
  Downloading harpoontools-0.1.6-py3-none-any.whl (16 kB)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from harpoontools) (2.31.0)
Collecting harpoon==0.1.6 (from harpoontools)
  Downloading harpoon-0.1.6-py3-none-any.whl (290 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 290.9/290.9 kB 6.0 MB/s eta 0:00:00
Requirement already satisfied: configparser in /usr/local/lib/python3.11/dist-packages (from harpoon==0.1.6->harpoontools) (6.0.0)
Requirement already satisfied: tweepy>=3.8.0 in /usr/local/lib/python3.11/dist-packages (from harpoon==0.1.6->harpoontools) (4.14.0)
Requirement already satisfied: passivetotal in /usr/local/lib/python3.11/dist-packages (from harpoon==0.1.6->harpoontools) (2.5.9)
Collecting beautifulsoup4==4.9.1 (from harpoon==0.1.6->harpoontools)
  Downloading beautifulsoup4-4.9.1-py3-none-any.whl (115 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.1/115.1 kB 10.7 MB/s eta 0:00:00
Collecting lxml==4.5.1 (from harpoon==0.1.6->harpoontools)
  Downloading lxml-4.5.1.tar.gz (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 23.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      /tmp/pip-install-grj_vwzm/lxml_5a076b421ae449f9a156df49b2fde879/setup.py:64: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources
      Building lxml version 4.5.1.
      Building without Cython.
      Error: Please make sure the libxml2 and libxslt development packages are installed.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

now i know that i shouldn't use `--break-system-packages` and so on, but building lxml from scratch is a pain in the back, so i use the system packages for that, much easier. except the lxml used by harpoon is different from the one used by harpoontools, because harpoontools hardcodes a 0.1.6 version dep on harpoon in setup.py. It also sets a different version in requirements.txt, for added confusion - *and* where are those version number from anyways?? i thought there were no tagged releases!...

i would recommend removing the versionned pin here.

**Comment by Te-k** [comment]
Thanks! There are actually versions in harpoon that are on [pypi](https://pypi.org/project/harpoon/#history), I just haven't made proper releases in github, but I'll fix that. 
So I have removed the conflicting dependencies in `requirements.txt`, is that enough to fix that issue?

**Comment by anarcat** [comment]
not really... if i `pip install harpoontools` now, it still tries to pull in harpoon 0.1.6 even though harpoon 0.1.7 is installed... i guess i need to install from git first, let me see if that fixes the issue.

**Comment by anarcat** [comment]
yeah, installing from git fixes the issue, so i guess you just need to punt a new release of harpoontools to pip to fix this, thanks!

**Comment by Te-k** [comment]
Ah right, that makes sense. I just pushed 0.1.7 to pip and made a release, it should solve the issue, thanks
